// Autocomplete
		$( function() {
		  var availableTags = [
		    "Andorra",
		    "United Arab Emirates",
		    "Afghanistan",
		    "Antigua and Barbuda",
		    "Anguilla",
		    "Albania",
		    "Armenia",
		    "Angola",
		    "Antarctica",
		    "Argentina",
		    "American Samoa",
		    "Austria",
		    "Australia",
		    "Aruba",
		    "Azerbaijan",
		    "Bosnia and Herzegovina",
		    "Barbados",
		    "Bangladesh",
		    "Belgium",
		    "Bulgaria",
		    "Bahrain",
		    "Burundi",
		    "Benin",
		    "Bermuda",
		    "Brunei Darussalam",
		    "Bolivia",
		    "Bonaire",
		    "Brazil",
		    "Bahamas",
		    "Bhutan",
		    "Botswana",
		    "Belarus",
		    "Belize",
		    "Democratic Republic of Congo (Kinshasa)",
		    "Central African Republic",
		    "Republic of Congo (Brazzaville)",
		    "Switzerland",
		    "Côte d'Ivoire (Ivory Coast)",
		    "Cook Islands",
		    "Chile",
		    "Cameroon",
		    "China",
		    "Colombia",
		    "Costa Rica",
		    "Cuba",
		    "Cabo Verde",
		    "Cyprus",
		    "Czech Republic",
		    "Germany",
		    "Denmark",
		    "Dominica",
		    "Dominican Republic",
		    "Algeria",
		    "Ecuador",
		    "Estonia",
		    "Egypt",
		    "Spain",
		    "Ethiopia",
		    "Finland",
		    "Fiji",
		    "France",
		    "United Kingdom",
		    "Georgia",
		    "Ghana",
		    "Gibraltar",
		    "Greenland",
		    "Guinea",
		    "Greece",
		    "Guatemala",
		    "Guam",
		    "Hong Kong",
		    "Honduras",
		    "Croatia",
		    "Haiti",
		    "Hungary",
		    "Canary Islands",
		    "Indonesia",
		    "Ireland",
		    "Israel, the West Bank and the Gaza Strip",
		    "India",
		    "Iraq",
		    "Iran",
		    "Iceland",
		    "Italy",
		    "Jamaica",
		    "Japan",
		    "Kenya",
		    "Cambodia",
		    "Kiribati",
		    "Comoros",
		    "Korea, North (DPRK)",
		    "Korea, South",
		    "Kuwait",
		    "Cayman Islands",
		    "Kazakhstan",
		    "Laos",
		    "Lebanon",
		    "Sri Lanka",
		    "Liberia",
		    "Luxembourg",
		    "Libya",
		    "Morocco",
		    "Monaco",
		    "Madagascar",
		    "Macedonia",
		    "Mali",
		    "Myanmar",
		    "Mongolia",
		    "Macao",
		    "Maldives",
		    "Mexico",
		    "Malaysia",
		    "New Caledonia",
		    "Niger",
		    "Nigeria",
		    "Nicaragua",
		    "Netherlands",
		    "Norway",
		    "Nepal",
		    "New Zealand",
		    "Oman",
		    "Panama",
		    "Peru",
		    "Papua New Guinea",
		    "Philippines",
		    "Pakistan",
		    "Poland",
		    "Puerto Rico",
		    "Portugal",
		    "Paraguay",
		    "Qatar",
		    "Romania",
		    "Serbia",
		    "Russia",
		    "Saudi Arabia",
		    "Solomon Islands",
		    "Sweden",
		    "Singapore",
		    "Slovenia",
		    "Senegal",
		    "Somalia",
		    "El Salvado",
		    "Syria",
		    "Thailand",
		    "Tunisia",
		    "Turkey",
		    "Trinidad and Tobago",
		    "Taiwan",
		    "Tanzania",
		    "Ukraine",
		    "Uganda",
		    "United States",
		    "Uruguay",
		    "Uzbekistan",
		    "Venezuela",
		    "Vietnam",
		    "Samoa",
		    "Yemen",
		    "South Africa",
		    "Zimbabwe"
		  ];
		  $( "#userCountry" ).autocomplete({
		    source: availableTags
		  });
		} );